// <auto-generated />
using System;
using ClinicManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Api.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260223141324_SeedDoctors")]
    partial class SeedDoctors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentCode")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7faed536-f799-4dcb-aa84-2d045890ff2a"),
                            Code = "BS001",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 412, DateTimeKind.Utc).AddTicks(5030),
                            LicenseNumber = "LIC001",
                            Specialty = "Nội tổng quát",
                            Status = 1,
                            UserId = new Guid("b890920a-966a-40ca-845d-006ac6d9a558")
                        },
                        new
                        {
                            Id = new Guid("3ba442e6-9f9d-4224-98e8-172e378851ea"),
                            Code = "BS002",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 412, DateTimeKind.Utc).AddTicks(5040),
                            LicenseNumber = "LIC002",
                            Specialty = "Da liễu",
                            Status = 1,
                            UserId = new Guid("59ab6848-1b08-469a-9870-eafb691e2f7a")
                        },
                        new
                        {
                            Id = new Guid("b0c27b0b-e73f-422e-900e-d5e40b4de28e"),
                            Code = "BS003",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 412, DateTimeKind.Utc).AddTicks(5050),
                            LicenseNumber = "LIC003",
                            Specialty = "Tai mũi họng",
                            Status = 1,
                            UserId = new Guid("daf60a66-994d-48ae-aa69-88171ef62066")
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a8a9bf3-145a-4b0e-a8ef-0e10e53ad092"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("1e24ab81-f2b0-4c2b-bc3a-4c8c73d83874"),
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("f200a9e1-1c5c-426f-a28a-4a88fb3a6362"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("d52fb928-a510-43ac-ba22-64fa7130d709"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55b18eb4-500c-496c-acc7-419c0ce53ce8"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 259, DateTimeKind.Utc).AddTicks(2480),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKlMV+tmoWKmkfQ1BljAjkyIk1Eu/XvCUhJlhi7VBWV/U1G8wrNdLzhPm4PECP7+BQ==",
                            PhoneNumber = "",
                            RoleId = new Guid("4a8a9bf3-145a-4b0e-a8ef-0e10e53ad092"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("b890920a-966a-40ca-845d-006ac6d9a558"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 297, DateTimeKind.Utc).AddTicks(8550),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEJpuB/lefsMZkWLTBLE5nlMPqg8zPx5A1/3jlj4qYpw/HI5735C0fdBED7ZasD679w==",
                            PhoneNumber = "",
                            RoleId = new Guid("1e24ab81-f2b0-4c2b-bc3a-4c8c73d83874"),
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = new Guid("59ab6848-1b08-469a-9870-eafb691e2f7a"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 335, DateTimeKind.Utc).AddTicks(8240),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEPKVTzfuFeP5m/GXiwpnY6+JBLqffrFUuC5LM7PIXJ2wzepJpa2/DjixPh9zhHcKJA==",
                            PhoneNumber = "",
                            RoleId = new Guid("1e24ab81-f2b0-4c2b-bc3a-4c8c73d83874"),
                            Username = "doctor2"
                        },
                        new
                        {
                            Id = new Guid("daf60a66-994d-48ae-aa69-88171ef62066"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 13, 24, 373, DateTimeKind.Utc).AddTicks(8990),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEDSEAXf6lm8Rp598qRwos94jm2UrXjDsTN+6NMU9pABu8o7GFZS0UgBo5NKMoe5pcA==",
                            PhoneNumber = "",
                            RoleId = new Guid("1e24ab81-f2b0-4c2b-bc3a-4c8c73d83874"),
                            Username = "doctor3"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicManagement.Api.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("ClinicManagement.Api.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
