// <auto-generated />
using System;
using ClinicManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Api.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260211050629_InitialClinic")]
    partial class InitialClinic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d35577f-f9b8-4259-b272-b4dcc64a0212"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bf96b140-00d1-49e8-81b7-a4a72a6d11ba"),
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("f3e32a71-4956-4316-988c-aaee62d78626"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("68590a3b-7378-4b39-b10c-4388b46bb20c"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b00cbca7-722b-4071-b601-aab336310eef"),
                            CreatedAt = new DateTime(2026, 2, 11, 5, 6, 29, 363, DateTimeKind.Utc).AddTicks(8170),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEJQVwAHyTB54YJY8LjmU73pqdpNbP4iqgsG7GGuN0oczrRPwgvdYjVWoWVLiAD/Dgg==",
                            PhoneNumber = "",
                            RoleId = new Guid("7d35577f-f9b8-4259-b272-b4dcc64a0212"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("ClinicManagement.Api.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
