// <auto-generated />
using System;
using ClinicManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Api.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260223141018_InitClinic")]
    partial class InitClinic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentCode")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e344a26e-de2c-4adc-adbc-7a8527ab774b"),
                            Code = "BS001",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 309, DateTimeKind.Utc).AddTicks(1720),
                            LicenseNumber = "LIC001",
                            Specialty = "Nội tổng quát",
                            Status = 1,
                            UserId = new Guid("b0aed582-58f5-4964-acd0-e3045a2bdf2b")
                        },
                        new
                        {
                            Id = new Guid("b8bc6a6b-008d-4c40-8905-73cce3488a0a"),
                            Code = "BS002",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 309, DateTimeKind.Utc).AddTicks(1730),
                            LicenseNumber = "LIC002",
                            Specialty = "Da liễu",
                            Status = 1,
                            UserId = new Guid("b23c8276-8b78-432e-8e2b-8b00424478c3")
                        },
                        new
                        {
                            Id = new Guid("bda96feb-e268-4162-99ae-74b63e84247c"),
                            Code = "BS003",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 309, DateTimeKind.Utc).AddTicks(1730),
                            LicenseNumber = "LIC003",
                            Specialty = "Tai mũi họng",
                            Status = 1,
                            UserId = new Guid("eb775b13-b4b2-407a-a7d0-b260beb596bf")
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dbabcf7-4707-4f5c-a5ac-6a920a5de1a0"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("44e02b51-6878-4381-aed5-3966c57ff58f"),
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("0dd796e9-3420-4f2e-8e70-335f0f158461"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("bfdc9e83-db44-4374-afdc-47310b201f72"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a53c617-10dc-4832-a950-32831cc00c01"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 162, DateTimeKind.Utc).AddTicks(7670),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEEVkjY0fRpanRMI4MdXWL7a29E87QsqLLgc703nxU4iLao6lS2QKVswWqAP00hozsw==",
                            PhoneNumber = "",
                            RoleId = new Guid("4dbabcf7-4707-4f5c-a5ac-6a920a5de1a0"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("b0aed582-58f5-4964-acd0-e3045a2bdf2b"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 199, DateTimeKind.Utc).AddTicks(6210),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEGBhKjjVDSMi4OKLEYQ4T0EbfOqEjcKn1hvM3AHxB0A4SShhZXmCqZSnDPMLzgS8Lw==",
                            PhoneNumber = "",
                            RoleId = new Guid("44e02b51-6878-4381-aed5-3966c57ff58f"),
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = new Guid("b23c8276-8b78-432e-8e2b-8b00424478c3"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 236, DateTimeKind.Utc).AddTicks(8050),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEN2XdQv6Erb5qxcLb9O6Q7cfizMbQ9KQeyz2ETK9vnnTi/6pY04Bl8i/kmIafAzuDA==",
                            PhoneNumber = "",
                            RoleId = new Guid("44e02b51-6878-4381-aed5-3966c57ff58f"),
                            Username = "doctor2"
                        },
                        new
                        {
                            Id = new Guid("eb775b13-b4b2-407a-a7d0-b260beb596bf"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 10, 18, 273, DateTimeKind.Utc).AddTicks(400),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEONmQ+jw6R1LtQlpcUeOGSVFRj5TVDJChjL7eSzTeJuohZYMpY2Bkwyh2xm1UQkUFw==",
                            PhoneNumber = "",
                            RoleId = new Guid("44e02b51-6878-4381-aed5-3966c57ff58f"),
                            Username = "doctor3"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicManagement.Api.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("ClinicManagement.Api.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
