// <auto-generated />
using System;
using ClinicManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Api.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260223145954_SeedStaffUser")]
    partial class SeedStaffUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentCode")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da4555ba-01ef-4274-970e-1315e2bfde22"),
                            Code = "BS001",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 689, DateTimeKind.Utc).AddTicks(9390),
                            LicenseNumber = "LIC001",
                            Specialty = "Nội tổng quát",
                            Status = 1,
                            UserId = new Guid("d2568579-de44-4a0a-bfaf-b481d0eccfe8")
                        },
                        new
                        {
                            Id = new Guid("50ef0ed6-74da-40d8-86a6-29d6a4a4f2e1"),
                            Code = "BS002",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 689, DateTimeKind.Utc).AddTicks(9400),
                            LicenseNumber = "LIC002",
                            Specialty = "Da liễu",
                            Status = 1,
                            UserId = new Guid("66f6e59e-9eb0-40bc-836f-a87fe2c86e7e")
                        },
                        new
                        {
                            Id = new Guid("02c66e35-b1ab-4c70-b832-36c7e16767e4"),
                            Code = "BS003",
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 689, DateTimeKind.Utc).AddTicks(9410),
                            LicenseNumber = "LIC003",
                            Specialty = "Tai mũi họng",
                            Status = 1,
                            UserId = new Guid("42ca2a8b-5852-40e0-998b-42ae7e80fd6a")
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0be8f2f-2100-4c9d-8649-dc598c29fbb8"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("1a749cab-5344-41f4-aa93-061051e7019b"),
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("845ff739-bead-48f2-a9ab-173b09f5e2f3"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("5311f7a0-fdf1-4cac-895a-bb3f186b694d"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("789dc153-6864-48a7-86b1-4d81848767ac"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 510, DateTimeKind.Utc).AddTicks(3240),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEO7LBSg3aNRt9D5Xv6jVIpl/caeyOBseJ7mx5KCpvrOcFf2B3OV97nzYyAM6PGNaGw==",
                            PhoneNumber = "",
                            RoleId = new Guid("d0be8f2f-2100-4c9d-8649-dc598c29fbb8"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("34f376b3-9901-43e6-864e-3de6f566b90e"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 546, DateTimeKind.Utc).AddTicks(2700),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAELhdMv6MdphuEnG5hoRg5FjuR4AMSjUW/dIb1k0XGt5jKt26m+u3vozivCXSWK2mew==",
                            PhoneNumber = "",
                            RoleId = new Guid("845ff739-bead-48f2-a9ab-173b09f5e2f3"),
                            Username = "staff1"
                        },
                        new
                        {
                            Id = new Guid("d2568579-de44-4a0a-bfaf-b481d0eccfe8"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 582, DateTimeKind.Utc).AddTicks(2950),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOm5W5K13sFaYQYd5S8h4wWmJm4m4gOqPGoIHCgNeUWAPAabuHATAz7/eENSC+3gsA==",
                            PhoneNumber = "",
                            RoleId = new Guid("1a749cab-5344-41f4-aa93-061051e7019b"),
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = new Guid("66f6e59e-9eb0-40bc-836f-a87fe2c86e7e"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 618, DateTimeKind.Utc).AddTicks(2150),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOypnQ1YbS3/IZxqzwncfd2+k5Zku5Og91dRDEytl32AbpJ5bA43Ooc+hBlMj3aXBw==",
                            PhoneNumber = "",
                            RoleId = new Guid("1a749cab-5344-41f4-aa93-061051e7019b"),
                            Username = "doctor2"
                        },
                        new
                        {
                            Id = new Guid("42ca2a8b-5852-40e0-998b-42ae7e80fd6a"),
                            CreatedAt = new DateTime(2026, 2, 23, 14, 59, 54, 654, DateTimeKind.Utc).AddTicks(670),
                            Email = "",
                            FullName = "",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEGekuHdO1O+UfJq4zP6ePcGBsna9krzyRh2CenLH0DHef0hsIxDHPJOo7Y+jYVXlKg==",
                            PhoneNumber = "",
                            RoleId = new Guid("1a749cab-5344-41f4-aa93-061051e7019b"),
                            Username = "doctor3"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Appointment", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicManagement.Api.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("ClinicManagement.Api.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.HasOne("ClinicManagement.Api.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagement.Api.Models.User", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
